# Generated by Django 4.0.2 on 2022-02-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('price', models.TextField(max_length=500)),
                ('verified_print', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='main_app.print')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main_app.print')),
            ],
        ),
        migrations.CreateModel(
            name='Mug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mugs', to='main_app.print')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main_app.print')),
            ],
        ),
    ]
