# Generated by Django 4.0.2 on 2022-02-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('cards', models.ManyToManyField(to='main_app.Card')),
                ('mugs', models.ManyToManyField(to='main_app.Mug')),
                ('photos', models.ManyToManyField(to='main_app.Photo')),
                ('puzzles', models.ManyToManyField(to='main_app.Puzzle')),
            ],
        ),
    ]
