# Generated by Django 4.0.2 on 2022-02-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_gift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gift',
        ),
        migrations.AlterField(
            model_name='print',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
