# Generated by Django 4.0.2 on 2022-02-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_giftset_created_at_giftset_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='giftset',
            name='verified_gift',
        ),
    ]
