# Generated by Django 4.0.2 on 2022-02-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_giftset_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftset',
            name='image',
        ),
    ]
