# Generated by Django 4.0.2 on 2022-02-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_giftset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftset',
            name='image',
            field=models.CharField(default=str, max_length=250),
        ),
    ]
